// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';
import { Document } from '@contentful/rich-text-types';

export interface IHomePageFields {
  /** afbeeldingen hero */
  afbeeldingenHero: Asset[];

  /** uitgelichte verhalen */
  uitgelichteVerhalen: Entry<{ [fieldId: string]: unknown }>[];

  /** uitgelichte items */
  uitgelichteItems: Entry<{ [fieldId: string]: unknown }>[];
}

/** alle content voor op de homepagina */

export interface IHomePage extends Entry<IHomePageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'homePage';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IStoriesFields {
  /** wedstrijd */
  wedstrijd?: string | undefined;

  /** verhaal */
  verhaal?: Document | undefined;

  /** thumbnail */
  thumbnail?: Asset | undefined;

  /** basis opstelling */
  basisOpstelling?: string | undefined;

  /** wissel spelers */
  wisselSpelers?: string | undefined;

  /** coach */
  coach?: string | undefined;

  /** score */
  score?: string | undefined;

  /** competitie */
  competitie?: string | undefined;

  /** datum */
  datum?: string | undefined;

  /** ronde */
  ronde?: string | undefined;

  /** plaatsnaam */
  plaatsnaam?: string | undefined;

  /** locatie */
  locatie: { lat: number; lon: number };

  /** wedstrijd ticket */
  wedstrijdTicket?: Entry<{ [fieldId: string]: unknown }> | undefined;

  /** programma boekje */
  programmaBoekje?: Entry<{ [fieldId: string]: unknown }> | undefined;
}

/** verhalen van ajax supporters */

export interface IStories extends Entry<IStoriesFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'stories';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ITicketAjaxAcMilan1995Fields {
  /** afbeelding van item */
  afbeelding: Asset;

  /** naam item */
  naamItem: string;

  /** beschrijving */
  beschrijving?: string | undefined;

  /** bijbehorende wedstrijd */
  bijbehorendeWedstrijd?: Entry<{ [fieldId: string]: unknown }> | undefined;

  /** verhaal item */
  verhaalItem?: string | undefined;
}

/** Hier komen alle collectibles */

export interface ITicketAjaxAcMilan1995 extends Entry<ITicketAjaxAcMilan1995Fields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'ticketAjaxAcMilan1995';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE = 'homePage' | 'stories' | 'ticketAjaxAcMilan1995';

export type IEntry = IHomePage | IStories | ITicketAjaxAcMilan1995;

export type LOCALE_CODE = 'en-US';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
